### ISSUE TITLE
Can I authenticate using username/pwd instead of PAT?

### ISSUE THREAD

**Issue by SamKacer** [paiqo/Databricks-VSCode#113]
Hello, thanks for developing this. 

For our workspace, generating personal access tokens is disabled. I will try to get the administrators to enable it, but that might take a while. For now I was hoping to connect using my username/pwd instead. 

If I configure databricks cli using username/pwd, the cli itself works fine and I can execute commands with it no problem. So, I was hoping if I set the VS code extension to use databricks cli as the connection manager, then I would be able to setup the extension to connect via the username/pwd configured in databricks cli.

However, instead I just get the following notification: "No connections have been configured yet! Please add a connection via the Databricks CLI config file before proceeding!"

It seems like without the token being in my databricks cli config file, the extension isn't able to connect, even though it could use the username/pwd to do so. For reference here is my databricks cli config (personal info omitted):

```
[DEFAULT]
host = <host>
jobs-api-version = 2.0
username = <username>
password = <pwd>
```

Could you please confirm whether ther is some way to get the extension to use the username/pwd or is only possible way of authenticating using PAT?

**Comment by gbrueckl** [comment]
Username/password via CLI config is currently not supported.

If you are on Azure you might want to try the new Azure Connection Manager - please see the readme for details.

Which cloud are you on?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: SamKacer ***@***.***>
Sent: Friday, November 25, 2022 3:50:39 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] Can I authenticate using username/pwd instead of PAT? (Issue #113)


Hello, thanks for developing this.

For our workspace, generating personal access tokens is disabled. I will try to get the administrators to enable it, but that might take a while. For now I was hoping to connect using my username/pwd instead.

If I configure databricks cli using username/pwd, the cli itself works fine and I can execute commands with it no problem. So, I was hoping if I set the VS code extension to use databricks cli as the connection manager, then I would be able to setup the extension to connect via the username/pwd configured in databricks cli.

However, instead I just get the following notification: "No connections have been configured yet! Please add a connection via the Databricks CLI config file before proceeding!"

It seems like without the token being in my databricks cli config file, the extension isn't able to connect, even though it could use the username/pwd to do so. For reference here is my databricks cli config (personal info omitted):

[DEFAULT]
host = <host>
jobs-api-version = 2.0
username = <username>
password = <pwd>


Could you please confirm whether ther is some way to get the extension to use the username/pwd or is only possible way of authenticating using PAT?

**Comment by SamKacer** [comment]
I believe I am on AWS, so unfortunately can't use the Azure connection manager.

Oh well, thanks for confirming. Hopefully I get access for generating PAT soon

**Comment by gbrueckl** [comment]
Actually i was not aware you can use Username/pw in CLI config but i think this should be easy to add. I will try something and update you here but it might take some tome as i do not have an AWS workspace

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
