### ISSUE TITLE
Connection details not being saved

### ISSUE THREAD

**Issue by MargaridaMC** [paiqo/Databricks-VSCode#119]
Hi 

I'm having a small issue with storing of the databricks connections details.
I've setup the connection as described under "Setup and Configuration (VSCode Connection Manager)" but it seems that vscode is not getting the details from the settings. Whenever I close and reopen vs code I always get a prompt to fill out the information again (screenshot included), even though in the settings the connection details are filled out. Is there an additional step needed to make sure vs code reads the connection details from the settings rather than having to fill them out manually each time?
![image](https://user-images.githubusercontent.com/23284323/208141172-fd0cabf6-817e-4b50-b534-fcc65361d7c0.png)

Many thanks

**Comment by gbrueckl** [comment]
Are you using the extension via vscode.dev?
If yes, this is still work in progress and currently not working

If you run vscode from your desktop please provide the logs

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: MargaridaMC ***@***.***>
Sent: Friday, December 16, 2022 5:19:01 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] Connection details not being saved (Issue #119)


Hi

I'm having a small issue with storing of the databricks connections details.
I've setup the connection as described under "Setup and Configuration (VSCode Connection Manager)" but it seems that vscode is not getting the details from the settings. Whenever I close and reopen vs code I always get a prompt to fill out the information again (screenshot included), even though in the settings the connection details are filled out. Is there an additional step needed to make sure vs code reads the connection details from the settings rather than having to fill them out manually each time?
[image]<https://user-images.githubusercontent.com/23284323/208141172-fd0cabf6-817e-4b50-b534-fcc65361d7c0.png>

Many thanks

**Comment by gbrueckl** [comment]
closing as no further feedback was provided
