### ISSUE TITLE
ERROR:  TypeError: Cannot read properties of undefined (reading 'language')

### ISSUE THREAD

**Issue by kimisikainai** [paiqo/Databricks-VSCode#180]
ERROR when run python file

%run  /A/B/py_file

**Comment by gbrueckl** [comment]
not sure but does this work in the Databricks service?
`%run` usually only works for notebooks but not for `.py` files (assuming you are using Files in Workspace)

**Comment by kimisikainai** [comment]
Our own code hasn't changed, and it could run in the previous version. However, it throws an error in the latest version.

**Comment by gbrueckl** [comment]
could you check the output of the extension if it reveals more information?
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/3689bbf6-05ec-4b2a-ada1-27f9f46823d2)

**Comment by gbrueckl** [comment]
so I also just tried this on Databricks and its not supported to run `.py` files their either using `%run`

it might be that it worked previously with this extension but this was rather a coincidence
as one of the goals of this extension is to support the very same code from VSCode and in Databricks directly - this is by design

regarding the error you are facing - I changed it and will now display the same/similar error message as you would also get when trying to execute a `.py` file using `%run` in the Databricks UI

**Comment by kimisikainai** [comment]
@gbrueckl  Thank you for this update. In general, most scenarios are now working, but errors still occur if there are nested conditions.

/A/B/file1 
/A/B/file2 ( This file contains a line of code.   %run /A/B/file1  )

when I execute  %run /A/B/file2  ,I get the following error.
File `'/A/B/file1'` not found.

**Comment by gbrueckl** [comment]
yes, thats a know limitation which is also described [here](https://github.com/paiqo/Databricks-VSCode?tab=readme-ov-file#notebook-kernel)
It would technically be doable but would require a lot of effort  - its in the backlog but with no ETA
