### ISSUE TITLE
Unable to connect Databricks Workspace

### ISSUE THREAD

**Issue by edwardLui-yusen** [paiqo/Databricks-VSCode#185]
Unable to execute notebook Azure Databricks workspaces in this awesome extension. Unlucky, this is no effect that after clicking the run button.
![image](https://github.com/paiqo/Databricks-VSCode/assets/158409244/c787de1f-b757-4458-a992-aa91a60d6517)

However, the official Databricks Extension is successfully connected with the workspace and able to be fetching the information and execute the notebook. In the setting, I double checked I am using the Databricks Extension as Connection manager.
![image](https://github.com/paiqo/Databricks-VSCode/assets/158409244/f144fa6b-a398-4c13-83c6-22208dc5ed02)

![image](https://github.com/paiqo/Databricks-VSCode/assets/158409244/40237317-711e-4a7c-8dca-d06ec21f832c)

**Comment by gbrueckl** [comment]
can you execute that notebook cell against the `Databricks Extension (generic)` Kernel/Cluster?

maybe try reopening VSCode - if you just changed the `Connection Manager`, a restart of VSCode might help

otherwise, please also check the logs 
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/7fa139c0-7ff5-48ad-a7c8-060d50586a98)

**Comment by edwardLui-yusen** [comment]
I only get python environment and Databricks Extension (generic) Kernel/

Here is the logs
![image](https://github.com/paiqo/Databricks-VSCode/assets/158409244/d6da739e-4a56-4f8f-a5d2-195c61bb762e)

**Comment by edwardLui-yusen** [comment]
issue fixed when I change to using `Azure` as connection manager.

**Comment by gbrueckl** [comment]
when using the `Databricks Extension` connection manager, you will only see that one generic kernel which represents the cluster that is selected in the Databricks Extensions - thats by design

Using `Azure` Connection Manager exposes all running clusters of the selected workspace as kernels

it would still be interesting why the `Databricks Extension` connection manager did not work - which kind of authentication did you use there?

**Comment by edwardLui-yusen** [comment]
I found that `Databricks Extension` is meta-service, I am not sure is it related.
![image](https://github.com/paiqo/Databricks-VSCode/assets/158409244/f7f690fe-8c94-44c4-bd7c-ae34909a2394)
