### ISSUE TITLE
Cluster tab not working

### ISSUE THREAD

**Issue by TomasKunka** [paiqo/Databricks-VSCode#26]
after pressing refresh on cluster tab error message pops up.
all the other tabs (workspace, jobs, dbfs, secrets) work fine.
tried in both stable and insiders.

`[paiqo.databricks-vscode]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api paiqo.databricks-vscode`

![image](https://user-images.githubusercontent.com/21249373/87099519-53f2a200-c24a-11ea-9ba2-b2f84f24591a.png)

Thank you!

**Comment by gbrueckl** [comment]
there was a similar issue once: https://github.com/paiqo/Databricks-VSCode/issues/7
dont know what actually solved it but it did not appear again since then
I also followed the solutions provided at https://code.visualstudio.com/api/advanced-topics/using-proposed-api

will do a release in the next hours - would be great if you could test again afterwards

**Comment by gbrueckl** [comment]
@TomasKunka  does the :ThumbsUp: mean it is working for you now? 
If yes, I would close this issue

**Comment by TomasKunka** [comment]
No, sorry for confusion. :ThumbsUp: meant, I can test again.

**Comment by TomasKunka** [comment]
v0.6.0 working now.
