### ISSUE TITLE
Use of existing Databricks Table

### ISSUE THREAD

**Issue by prabgemini** [paiqo/Databricks-VSCode#28]
Can we have the functionality of showing and also using the databricks tables in the code on vscode?

**Comment by gbrueckl** [comment]
Hi @prabgemini ,

unfortunately the Databricks REST API does not provide any information about databases or tables.
This is probably because this would require a running cluster.
As this extension only interacts with the Databricks REST API and offers a nice GUI, databases and tables will not be available in VSCode until they are exposed via the REST API.

you can still query existing tables and use SQL via Spark code if you set up Databricks Connect for VS Code

regards,
-gerhard
