### ISSUE TITLE
Can't Seem to Get the Databricks-Connect and the Databricks Extension to Work on My Machine

### ISSUE THREAD

**Issue by briancuster** [paiqo/Databricks-VSCode#37]
I have installed the databricks extension on my machine and have tried to set up my workspace with the extension.  However, everytime I enter the information that is required, it simply disappears and nothing happens.  I am not connected to my workspace.  I've tried everything I know to do and it just doesn't work for me.  Also, I have run into trouble trying to set up databricks-connect.  I always run into trouble when I test the configuration.  I continually get the error message "Java gateway process exited before sending its port number" whenever I test with databricks-connect.  I'm not able to get either tool to work well with my environment.

**Comment by gbrueckl** [comment]
Can't really help you with Databricks-connect issues as this has nothing to do with the extension (at least technically)
For your other issues:
The settings disappear because they are moved to the User settings so they are not accidentally checked in to git. In your workspace settings you will see a reference to the User settings

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
