### ISSUE TITLE
Subfolders within Repos are not Synced

### ISSUE THREAD

**Issue by AlexPapas** [paiqo/Databricks-VSCode#60]
It seems there is an issue with syncing the local folders with the git repos on Databricks

Databricks folder structure
![image](https://user-images.githubusercontent.com/29041538/136079277-a77d32c4-8224-439a-936e-815976513a04.png)

Local Vs Code

![image](https://user-images.githubusercontent.com/29041538/136079385-96ccdc15-5d6d-418d-8553-19002828ad8f.png)

As you can see it shows that has downloaded the content but in reality only the first folder is synced - the content of the folder (actual repo) is not there

My settings are:
`    "databricks.connection.default.apiRootUrl": "https://XXX.azuredatabricks.net/",
    "databricks.connection.default.displayName": "MyDataBricks",
    "databricks.connection.default.localSyncFolder": "C:\\Databricks",
    "databricks.lastActiveConnection": "MyDataBricks",
    "databricks.connection.default.personalAccessTokenSecure": {
        "keyTarSettingName": "MyDataBricks-API-Token"
    },
    "databricks.connection.default.exportFormats": {
        "Scala": ".scala",
        "Python": ".py.ipynb",
        "SQL": ".sql",
        "R": ".r"
    },
}`

**Comment by gbrueckl** [comment]
Hi AlexPapas,

thanks for reporting this. I assume that git-repo-folders are not listed when calling the Workspace API hence they also cannot be downloaded. 
But I need to verify this - probably tomorrow and then I will come back to you

-gerhard

**Comment by gbrueckl** [comment]
I just published v0.8.7 which should fix this issue 
please confirm back here and close the issue if everything works for you

**Comment by gbrueckl** [comment]
regarding 3. - you can change 
`"databricks.connection.default.exportFormats": { "Scala": ".scala", "Python": ".py.ipynb", "SQL": ".sql", "R": ".r" }`
to 
`"databricks.connection.default.exportFormats": { "Scala": ".scala", **"Python": ".py"**, "SQL": ".sql", "R": ".r" }`
to download the files as `.py` and support better comparison between versions

1. and 2. are not really related to this extension
we cannot derive any of those settings from Databricks

but I guess in your usecase it would make more sense to sync your local changes directly to the GIT provider instead of going through Databricks

**Comment by gbrueckl** [comment]
the initial issue was fixed and the other questions where answered - if you need anything else, please open another ticket (one per issue)

thanks
-gerhard
