### ISSUE TITLE
Displaying html content when running against a Databricks cluster

### ISSUE THREAD

**Issue by sebastienlanglois** [paiqo/Databricks-VSCode#90]
Hi!
First of all, thank you for this great library!

I am using v1.0.0 to run python code against a databricks cluster. I am usually able to display HTML either in Jupyter or in Databricks directly such as this example:
![image](https://user-images.githubusercontent.com/42305216/185652620-04b238a4-238f-4b5d-87c8-fe287970d6db.png)

Unfortunately, when using this extension to run python code on a Databricks cluster, the same command renders pure html instead of the expected output
![image](https://user-images.githubusercontent.com/42305216/185652945-9449dc98-94b8-4898-a5f6-f45a20ecb3a0.png)

Was wondering if it was possible to display HTML correctly. Note that displayHTML does not work and is not required when used directly in Databricks in this instance.

Thank you!

**Comment by gbrueckl** [comment]
so there is a known issue with displayHTML() now working the same way as it does in Databricks
but this issue is with the underlying API that we use so we cannot really change this ourselves - however, i already addressed it at Databricks 

I also implemented a new logic which checks text-output for most common HTML tags (<html>, <div>, <table>) and if they appear in the text, an additional HTML output is generated 
It is however not guaranteed that this will work with any HTML

**Comment by gbrueckl** [comment]
v1.1.0 is now available for download from this github repo - it will show the output as HTML even if the Databricks API just returns it as "text"
https://github.com/paiqo/Databricks-VSCode/releases/tag/v1.1.0

It is not yet published to the VSCode gallery so please install in manually and run your tests 

PS: it also includes a lot of other new features!

**Comment by gbrueckl** [comment]
closed as resolved
