### ISSUE TITLE
Non persisting PA Token

### ISSUE THREAD

**Issue by morningtundra** [paiqo/Databricks-VSCode#98]
I am using Databricks VSCode v1.1.4 within VSC 1.68.1 in an enterprise environment (MS Windows).

For some reason my Personal Access Security Token will not permanently save in the extension settings beyond the current session. I have to paste the token in each time I launch VSC and it works fine until the session (Workspace) is closed. Reopen the Workspace or restart VSC and the PAT is gone.

*C:\Users\me\AppData\Roaming\Code\User\settings.json* seems to be getting wiped or over written.

Is anyone else experiencing this? Or just a local environment issue?
 
![Annotation 2022-10-05 164618](https://user-images.githubusercontent.com/49348167/194170010-29fef662-7b9b-4ac2-86e9-73c8ae4dcfed.png)

**Comment by gbrueckl** [comment]
this is by design to make sure the plain text token is not stored in the settings file
instead, the value will be stored in your systems key chain (e.g Windows Credential Manager) and the reference to that secret is stored in `databricks.default.personalAccessTokenSecure`
when you open VSCode again, it will take the token from there without any further manual interaction from your side

if this is still not working, please check the `Edit in settings.json` of the `Personal Access Token Secure` setting 

it might also help to check the VSCode output channel for further information
![image](https://user-images.githubusercontent.com/11884402/196623048-67a8d45c-ade9-482b-bfca-d2e94b519802.png)

**Comment by gbrueckl** [comment]
any update to this issue?

**Comment by morningtundra** [comment]
Thank you for following up. Unfortunately, I can not access or edit my Windows Credential Manager (enterprise controls). For now, I have just to reenter the PAT each time I start a working session.

**Comment by gbrueckl** [comment]
if the Windows Credential Manager does not work for you, you may try to use the DAtabricks CLI Configuration Manager instead:
![image](https://user-images.githubusercontent.com/11884402/198208313-c7d74a7b-d1ea-4405-aa76-b7778cbaafbe.png)
the Databricks CLI stores your credentials in a text file in your users home directory as `.databrickscfg`

for more information please also refer to the README: https://github.com/paiqo/Databricks-VSCode#setup-and-configuration-databricks-cli-connection-manager

**Comment by gbrueckl** [comment]
Closing as not related to the extension and alternative provided
